# introduction

The Black-Litterman (BL) asset allocation model is pretty amazing. It consists of three brilliant ideas, whose interplay is a brilliant idea on its own. It is (1) a Bayesian econometrics model (2) with a very smart choice of the prior and the data, and (3) an asset allocation model. Neither of the ideas feels out of place, and neither was introduced just for the sake of it.

In this notebook, I would like to visualize the Bayesian dimension of Black-Litterman that was pointed out (among others) by [Kolm and Ritter (2017)](https://cims.nyu.edu/~ritter/kolm2017bayesian.pdf). I will use a library for Bayesian inference &ndash; `Turing.jl` &ndash; to numerically solve the example in [He and Litterman (1999)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=334304), and, of course, will arrive at the same values as in the closed-form solution derived by the original inventors.

# bayesian econometrics recap
In the Bayesian econometrics, randomness is nested: the observed data is assumed to be generated by a stochastic process of some parameters, and the parameters themselves are assumed stochastic! This way, the data produced would be random even if the parameters were fixed and known, but since they aren't, the data becomes... twice as random? Anyway, the Bayesian econometrician starts with a prior belief about the distribution of the parameters, then checks the likelihood of observing the data if that belief is correct, and updates the belief accordingly &ndash; stronger so if the likelihood is low. The end result is the tug-of-war between the prior and the data.

# black-litterman model recap
Black and Litterman ponder how a portfolio manager could incorporate (possibly contradicting) views about expected returns (e.g from different analysts) into the mean-variance optimization problem. Neat! They decide to do the following: 
- treat the expected returns as a random variable; 
- make the views a (conveniently linear) function of that random variable plus some noise; 
- assume the Normal distribution for all random variables;
- enjoy a closed-form solution for the mean and covariance of asset returns because of the linearity and gaussianity;
- plug the mean and covariance into the mean-variance optimization and call it a day (not really, as they also flex the market equilibrium and currency hedging in their model).

# black-litterman model through bayesian lens
A distribution parameter is a random variable, you say? Sure sounds Bayesian! The only missing piece is the data that the econometrician would use to update the prior, but the views can play this role. After all, as Kolm and Ritter (2017) write:

> we suggest thinking of a portfolio manager's [view] as an “observation of the future” in which the measuring device is a rather murky and unreliable crystal ball. Only in this way is it analogous to the noisy measurements in experimental design which much of statistics is designed to model.

The views can be just one view, they can be contradicting views, they can be indirect, i.e. a function of the parameter of interest, etc. &ndash; in other words, behave just like data. 

After the prior is updated, the mean and variance of the posterior are used in the Markowitz optimization. Modern techniques allow to efficiently sample from the posterior, thus eliminating the need in closed-form solutions and allowing to extend the original setting.

Here is the model in detail:

1. To perform the Markowitz optimization, the expected value $\mu_r$ and the covariance matrix $\Sigma_r$ of asset returns are needed;
2. $\Sigma_r$ is assumed to be known or at least estimated with very high precision;
3. $\mu_r$, however, are a vector-valued random variable, initially believed to follow the (multivariate) Normal distribution with mean $\Pi$ and covariance $\Sigma_{\mu} = \tau \Sigma_r$; $\Pi$ is taken to be the expected returns which would without any other information result in the market portfolio being mean-variance efficient; this is beyond the scope of this piece, and it is suffices to assume $\Pi$ is known;
4. the views are data points which can tell a little more about the distribution of $\mu_r$, since they depend on it in the following form: 
    $$
        P \mu_r = q + \varepsilon_q,
    $$ 
    where $\varepsilon$ is a random variable introducing the noise (of course, Normally distributed!)
5. finally, the update of the prior belief from (3) is made based on the views in the Bayesian fashion: intuitively, the updated distribution will reflect the views, the stronger so, the more numerous and less noisy they are;
6. finally, we don't need the whole updated distribution of $\mu_r$, but only its mean because nesting Normal random variables preserves the mean of the innermost variable, and because, bar the covariance, _nothing else matters_ for the mean-variance optimization.

Black and Litterman provide a closed-form solution for the mean of the asset returns (which turns out to be the mean of the updated distribution of $\mu_r$) and their covariance (which turns out to be updated, too). The solution is derived from some simple mathematics without references to prior, conjugates, posterior, likelihoods and all that Bayesian stuff...

# implementation as a bayesian update problem
...but where is fun is that? Let's solve the problem numerically using the outstanding `Turing.jl`, and confirm that Black-Litterman is essentially Black-Litterman-Bayes!

First, recreate the environment, where `Turing` and other necessary packages are installed, and import them.

In [1]:
using Pkg

Pkg.instantiate()

In [3]:
using Turing, Distributions, MCMCChains

Then, let's import some helper function, like the ones fetching the data from He and Litterman (1999).

In [2]:
# datafeed functions and nearest_pd_matrix
include("src_julia/datafeed.jl")
include("src_julia/utilities.jl")

nearest_pd_matrix (generic function with 1 method)

Now, let's load data from that paper: the covariance matrix is constructed using the correlation structure from Table 1 and the standard deviations from Table 2; the market portfolio weights are from Table 2.

In [4]:
# covariance; can be numerically non-hermitian, so let's fix it
const Σ_r = nearest_pd_matrix(get_covariance());

# Pi, the mean of expected returns' distribution, in fractions of 1
const Π = get_table(2)[:, :Pi] / 100;

n_assets = length(Π);

println("covariance:"); flush(stdout)
display(round.(Σ_r, digits=4))

covariance:


7×7 Matrix{Float64}:
 0.0256  0.0159  0.019   0.0223  0.0148  0.0164  0.0147
 0.0159  0.0412  0.0334  0.036   0.0132  0.0247  0.0296
 0.019   0.0334  0.0615  0.0579  0.0185  0.0388  0.031
 0.0223  0.036   0.0579  0.0734  0.0201  0.0421  0.0331
 0.0148  0.0132  0.0185  0.0201  0.0441  0.017   0.012
 0.0164  0.0247  0.0388  0.0421  0.017   0.04    0.0244
 0.0147  0.0296  0.031   0.0331  0.012   0.0244  0.035

Also, define parameters as in the paper: 
  - the scaling factor $\tau$ for the covariance in the prior distribution of the $\mu_r$ is set to 0.05; 
  - the variance of the view about the German market $\omega$ is set via $\omega/\tau = 0.021$.

In [5]:
# variance scaling for the expected returns prior
const τ = 0.05;

# (relative) view uncertainty
const omega_through_tau = 0.021;

# view uncertainty
const ω = omega_through_tau * τ;

Finally, define the necessary $P$ and $Q$ matrices for the view about the German market outperforming the rest of Europe by 5%; $P$ is taken from Table 4. Since we are dealing with the single view, it's easier to define $P$ and $Q$ as vectors:

In [6]:
# view that ger outperformce market cap-weighted fra+gbr by 5% (from table 3)
const p = get_table(4)[:, :p] / 100;
const q = 0.05;

println("long-short portfolio with the view on german market:")
println(p)

long-short portfolio with the view on german market:
[0.0, 0.0, -0.295, 1.0, 0.0, -0.705, 0.0]


Now, let's set up a Bayesian model by:

1. treating the expected returns of the assets as a random variable with a prior distribution;
2. treating the view about the German market as the realization of a random variable connected to the expected returns;
3. adjusting the distribution of returns.

$$
\begin{gather}
    \mu_r \sim N(\Pi, \tau \Sigma_r) \\
    q | \mu_r \sim N(P'\mu_r, \omega) \\
    r | \mu \sim N(\mu_r, \Sigma).
\end{gather}
$$

In [7]:
# black-litterman bayesian model
@model function blb(_q)

    # prior on mu
    μ_r ~ MvNormal(Π, τ*Σ_r);

    # given mu, the views are distributed as:
    _q ~ Normal(dot(p, μ_r), sqrt(ω));
    
    # condition the model on data
    return _q
end

blb (generic function with 2 methods)

Sampling from the posterior requires providing the data to the function above and specifying the sampler, the number of iterations etc.

In [8]:
chain = sample(
    blb(q),  # condition the model on the data
    NUTS(),  # sampler
    40000,   # number of iterations
    progress = false
);

┌ Info: Found initial step size
│   ϵ = 0.0125
└ @ Turing.Inference /home/ipozdeev/.julia/packages/Turing/7Nd32/src/mcmc/hmc.jl:191


To retrieve the posterior estimate of $\mu_r$, `describe` can be used. Let's compare this estimate to the one from the closed-form solution provided in the paper.

In [9]:
post_est, _ = describe(chain);

# print the posterior mu, rounded and in %
μ_bar = round.(post_est[:, :mean] * 100, digits=1);

# the value from table 4 in the paper
μ_bar_exog = get_table(4)[:, :mu_bar];

print(DataFrame(:μ_bar => μ_bar, :μ_bar_paper => μ_bar_exog))

7×2 DataFrame
 Row │ μ_bar    μ_bar_paper 
     │ Float64  Float64     
─────┼──────────────────────
   1 │     4.3          4.3
   2 │     7.6          7.6
   3 │     9.4          9.3
   4 │    11.1         11.0
   5 │     4.5          4.5
   6 │     7.0          7.0
   7 │     8.1          8.1

Bar numerical differences, a perfect match! Now, what about the covariance $\Sigma_r$? To get to it, we can sample enough values from the posterior distribution of $r$ and use the good ol' sample covariance of those values; the former is done by rewriting the `blb` function slightly (see the [Turing reference](https://turing.ml/dev/docs/using-turing/guide#treating-observations-as-random-variables) for details):

In [10]:
# black-litterman bayesian model
@model function blb_with_r(q, _r)

    if _r === missing
        # initialize `q` if missing
        _r = Vector{Float64}(undef, n_assets);
    end

    # prior on mu
    μ_r ~ MvNormal(Π, τ* Σ_r);

    # given mu, the views are distributed as:
    _q ~ Normal(dot(p, μ_r), sqrt(ω));
    
    # given mu, the returns are distributed as:
    _r ~ MvNormal(μ_r, Σ_r);
    
    # condition the model on data
    return q
end

blb_with_r (generic function with 2 methods)

In [11]:
# sample from the posterior of r
chain = sample(
    blb_with_r(q, missing), 
    NUTS(), 
    40000, 
    progress = false
);

┌ Info: Found initial step size
│   ϵ = 0.0125
└ @ Turing.Inference /home/ipozdeev/.julia/packages/Turing/7Nd32/src/mcmc/hmc.jl:191


In [12]:
# extract the simulated values from the chain object
r_sim = DataFrame(chain)[!, (n_assets+1+3):(n_assets+1+3+n_assets-1)];

println("returns sampled from the posterior distribution (first 6 rows)")
print(round.(r_sim[1:6, :], digits=4))

returns sampled from the posterior distribution (first 6 rows)
6×7 DataFrame
 Row │ _r[1]    _r[2]    _r[3]    _r[4]    _r[5]    _r[6]    _r[7]   
     │ Float64  Float64  Float64  Float64  Float64  Float64  Float64 
─────┼───────────────────────────────────────────────────────────────
   1 │  0.0935   0.2904  -0.1547   0.0114  -0.1259  -0.0739   0.1092
   2 │  0.0739   0.2525   0.1991   0.1537  -0.1734   0.1147   0.0074
   3 │  0.3742   0.2958   0.1598   0.4998   0.4319   0.3038   0.0015
   4 │  0.0249   0.0144   0.5413   0.3906   0.4885   0.3692   0.2553
   5 │  0.1325   0.2318   0.3116   0.1128  -0.0955   0.1748   0.4691
   6 │  0.0627   0.0997   0.5044   0.4737   0.1849   0.2274   0.1291

Now we can just estimate the covariance matrix of these values.

In [13]:
Σ_r_post = cov(Matrix(r_sim));

display(round.(Σ_r_post, digits=4))

7×7 Matrix{Float64}:
 0.027   0.0167  0.0202  0.0237  0.0158  0.0174  0.0156
 0.0167  0.0434  0.0357  0.0383  0.0145  0.0264  0.0314
 0.0202  0.0357  0.0653  0.0615  0.02    0.0415  0.033
 0.0237  0.0383  0.0615  0.0779  0.0219  0.0448  0.0353
 0.0158  0.0145  0.02    0.0219  0.0471  0.0185  0.0131
 0.0174  0.0264  0.0415  0.0448  0.0185  0.0424  0.026
 0.0156  0.0314  0.033   0.0353  0.0131  0.026   0.0368

Compared to the original covariance matrix, the posterior is larger in magnitude...

In [14]:
display(round.(Σ_r, digits=4))

7×7 Matrix{Float64}:
 0.0256  0.0159  0.019   0.0223  0.0148  0.0164  0.0147
 0.0159  0.0412  0.0334  0.036   0.0132  0.0247  0.0296
 0.019   0.0334  0.0615  0.0579  0.0185  0.0388  0.031
 0.0223  0.036   0.0579  0.0734  0.0201  0.0421  0.0331
 0.0148  0.0132  0.0185  0.0201  0.0441  0.017   0.012
 0.0164  0.0247  0.0388  0.0421  0.017   0.04    0.0244
 0.0147  0.0296  0.031   0.0331  0.012   0.0244  0.035

...by &ndash; surprize? &ndash; $(1 + \tau)$!

In [15]:
display(round.(Σ_r_post ./ Σ_r, digits=2))

7×7 Matrix{Float64}:
 1.05  1.05  1.07  1.06  1.07  1.06  1.06
 1.05  1.05  1.07  1.06  1.1   1.07  1.06
 1.07  1.07  1.06  1.06  1.08  1.07  1.07
 1.06  1.06  1.06  1.06  1.09  1.06  1.07
 1.07  1.1   1.08  1.09  1.07  1.09  1.09
 1.06  1.07  1.07  1.06  1.09  1.06  1.07
 1.06  1.06  1.07  1.07  1.09  1.07  1.05

# extensions

Given it's so easy to define Bayesian models in Turing, let's try a tricky one. Now, assume that the view is for the global minimum variance portfolio (GMVP), which the investor believes should be the 1/N portfolio.

To tackle this, we need to remember that the GMVP is a function of the covariance matrix only, treat the covariance matrix as a random variable, put a prior on it, and specify the likelihood of observing a certain GMVP given a covariance matrix. A good prior for the covariance matrix is the Wishart distribution, possibly centered on the covariance that the investor already has in mind (e.g. the sample covariance); a good distribution to use to calculate the likelihood is the Dirichlet distribution, which is defined on the set of vectors summing up to 1 and looking like portfolio weights. Strictly speaking:

$$
\Sigma_r \sim \textnormal{Wish}(\Sigma) \\
w | \Sigma_r = \underset{w \gt 0}{\argmin} \ w' \Sigma_r w \\
w \sim \textnormal{Dir}(\gamma \times \frac{1}{N} \mathbb{1}_{\{N\}}),
$$

where $\gamma$ is a scaling factor for the Dirichlet parameter: the larger the factor, the more concentrated the distribution becomes around $\frac{1}{N}$.

In [110]:
using Ipopt, JuMP

# function get_w_gmvp(_covmat)
#     n = size(_covmat, 1);
#     model = Model(Ipopt.Optimizer);

#     # set up and constraint variable to be sort of > 0
#     @variable(model, weights[1:n] .>= 1e-08);

#     @objective(model, Min, dot(weights, _covmat, weights));

#     @constraint(model, sum(weights) == 1);

#     set_silent(model);

#     optimize!(model)

#     return value.(weights)
# end

function get_w_gmvp(covmat_inv)
    
    res = sum(covmat_inv, dims=1)[1, :] ./ sum(covmat_inv);

    return res
end

w_gmvp = get_w_gmvp(inv(Σ_r));
print(round.(w_gmvp, digits=2))

[0.47, 0.1, -0.01, -0.22, 0.19, 0.22, 0.25]

In [17]:
using Distributions

In [61]:
A = vcat(Matrix(I, n_assets-1, n_assets-1), -ones(1, n_assets-1));
b = [zeros(n_assets-1); [1]];
w_prior_sigma = A * (Matrix(I, n_assets-1, n_assets-1) * 0.0030) * A';
w_prior_sigma = nearest_pd_matrix(w_prior_sigma);

In [68]:
wishart_df = 10;
dirichlet_scaling = 10;

# @model function blb_gmvp(w_gmvp)

#     global Π, Σ_r

#     # prior on covariance
#     Σ_r_prior ~ Wishart(wishart_df, Σ_r);

#     _w_gmvp = get_w_gmvp(Σ_r_prior);

#     # condition the model on data
#     w_gmvp ~ Dirichlet(_w_gmvp * dirichlet_scaling);
    
#     return w_gmvp
# end

@model function blb_gmvp(w_gmvp)

    global Σ_r

    # prior on covariance
    Σ_r_prior ~ Wishart(wishart_df, Σ_r);

    _w_gmvp = get_w_gmvp(inv(Σ_r_prior));

    # condition the model on data
    w_gmvp ~ MvNormal(_w_gmvp, w_prior_sigma);
    
    return w_gmvp
end

blb_gmvp (generic function with 2 methods)

In [114]:
chain = sample(
    blb_gmvp(ones(n_assets) / n_assets), 
    MH(), 400000, 
    progress = false
);

In [115]:
post_est, _ = describe(chain);
Σ_r_post = reshape(post_est[:, :mean], n_assets, n_assets) / wishart_df;

In [116]:
get_w_gmvp(inv(Σ_r_post))

7-element Vector{Float64}:
 0.14194412386421523
 0.14581880422116655
 0.11788664017595694
 0.07240006546445665
 0.15977000924647972
 0.1447233610864543
 0.21745699594127058

In [37]:
vcv_new = rand(Wishart(10, Σ_r));
rho_new = vcv_new ./ sqrt.(reshape(diag(vcv_new), :, 1)) ./ 
    sqrt.(reshape(diag(vcv_new), 1, :));


In [38]:
sigma = log.(sqrt.(diag(Σ_r)));
exp.(rand(MvLogNormal(sigma, Matrix(I, n_assets, n_assets) ./ 10)))

7-element Vector{Float64}:
 1.3108603386807525
 1.243420709268817
 1.1777285131627708
 1.3920181156956342
 1.288242758423971
 1.2024213267903576
 1.2725223304939104

In [39]:
sqrt.(diag(Σ_r))

7-element Vector{Float64}:
 0.16
 0.20299999999999999
 0.24799999999999994
 0.27099999999999996
 0.21
 0.19999999999999998
 0.18699999999999997

In [40]:
sigma

7-element Vector{Float64}:
 -1.8325814637483102
 -1.5945492999403499
 -1.394326532817155
 -1.3056364581024362
 -1.5606477482646683
 -1.6094379124341005
 -1.6766466621275506